### ISSUE TITLE
the coordinates of Spatial transcriptomic simulation data~

### ISSUE THREAD

**Issue by lzygenomics** [rdong08/spatialDWLS_dataset#3]
Dear @rdong08 
Thanks for the spatial transcriptome simulation data you provide~! It's really helpful~and...I have some problems..at first, I thought the coordinate was the column name in the count matrix, and then I found that some column names have the same two digits, so Could you please provide the coordinate information of simulation data~? Thank you very much~!

**Comment by rdong08** [comment]
Yes, the col names are the coordinates. I double checked the data with name "simulated_seqFISH_grid_norm_exp.txt" and not found the duplicated coordinates. Please note that there are some minus value in the column.

**Comment by lzygenomics** [comment]
> 
Wow, thanks for your quick response~Sorry I didn't notice the minus sign....
Thanks for your help, that's very kind of you ！
