### ISSUE TITLE
The annotation problem of simulated data

### ISSUE THREAD

**Issue by leihouyeung** [rdong08/spatialDWLS_dataset#5]
Dear Rui,

your simulation method is really helpful for me. And I have a question about the annotation.
Did you find the simulated data from https://github.com/CaiGroup/seqFISH-PLUS ?
If so, in the file "celltype_annotations.zip", it has Louvain clusters number and how did you transfer them into 6 annotated clusters? Could you please guide me detailedly on how to get the annotation of the cells in the cortex?
Thanks so much for your help!

**Comment by rdong08** [comment]
Hi,

I annotated the clusters by code from "https://rubd.github.io/Giotto_site/articles/mouse_seqFISH_cortex_200914.html". Please follow the Giotto steps for the annotation. Here is the detailed method, which is in Genome Biology paper "Giotto: a toolbox for integrative analysis and visualization of spatial expression data".

To match the cell-type annotations between seqFISH+ and scRNAseq data, we aggregated the major clusters annotated by Giotto pipeline. “L2/3 eNeuron,” “L4 eNeuron,” “L5 eNeuron,” and “L6 eNeuron” were marked as excitatory neuron (eNeuron). “Adarb2 iNeuron” and “Lhx6 iNeuron” were marked as inhibitory neurons (iNeuron). “Endothelial” and “mural” were marked as “endothelial_mural”.

**Comment by leihouyeung** [comment]
Thanks so much
